project:
  type: website
  output-dir: docs

website:
  title: "Christine Hou"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: github
        href: https://github.com/christinehou11

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

